// <auto-generated />
using System;
using ContractDevApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractDevApi.Migrations
{
    [DbContext(typeof(ContractDevContext))]
    [Migration("20260414111916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "title", new[] { "developer", "client", "both" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractDevApi.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId")
                        .HasName("pk_skills");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("ContractDevApi.Models.SocialConnection", b =>
                {
                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("user_account_id");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("facebook_link");

                    b.Property<string>("GithubLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("github_link");

                    b.Property<string>("LinkedinLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linkedin_link");

                    b.Property<string>("UserSocialEmailLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_social_email_link");

                    b.Property<string>("XLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("x_link");

                    b.HasKey("UserAccountId")
                        .HasName("pk_social_connections");

                    b.ToTable("social_connections", (string)null);
                });

            modelBuilder.Entity("ContractDevApi.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAccountId"));

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<string>("SecurityAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_answer");

                    b.Property<string>("SecurityQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_question");

                    b.Property<string>("UserSignupEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_signup_email");

                    b.HasKey("UserAccountId")
                        .HasName("pk_user_accounts");

                    b.HasIndex("UserSignupEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_user_signup_email");

                    b.ToTable("user_accounts", null, t =>
                        {
                            t.HasCheckConstraint("allowed_email_providers", "user_signup_email ILIKE '%@gmail.com' OR user_signup_email ILIKE '%@outlook.com' OR user_signup_email ILIKE '%@icloud.com' OR user_signup_email ILIKE '%@yahoo.com' OR user_signup_email ILIKE '%@hotmail.com' OR user_signup_email ILIKE '%@proton.me' OR user_signup_email ILIKE '%@protonmail.com' OR user_signup_email ILIKE '%@pm.me'");
                        });
                });

            modelBuilder.Entity("ContractDevApi.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserProfileId"));

                    b.Property<bool?>("AvailableForWork")
                        .HasColumnType("boolean")
                        .HasColumnName("available_for_work");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bio");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("HidePhoneNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_phone_number");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name");

                    b.Property<bool?>("OfferingWork")
                        .HasColumnType("boolean")
                        .HasColumnName("offering_work");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePictureExtension")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("profile_picture_extension");

                    b.Property<string>("ProfilePictureFilepath")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("profile_picture_filepath");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserTitle")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_title");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<bool?>("UsernameDisplay")
                        .HasColumnType("boolean")
                        .HasColumnName("username_display");

                    b.HasKey("UserProfileId")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_user_profiles_user_account_id");

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("allowed_descriptions", "description ILIKE 'developer' OR description ILIKE 'client' OR description ILIKE 'both'");
                        });
                });

            modelBuilder.Entity("ContractDevApi.Models.UserRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rating_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RatingId"));

                    b.Property<int>("CollaborationScore")
                        .HasColumnType("integer")
                        .HasColumnName("collaboration_score");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("integer")
                        .HasColumnName("communication_score");

                    b.Property<int>("PaymentReliabilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("payment_reliability_score");

                    b.Property<int>("RecommendationScore")
                        .HasColumnType("integer")
                        .HasColumnName("recommendation_score");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewee_id");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("TimeManagementScore")
                        .HasColumnType("integer")
                        .HasColumnName("time_management_score");

                    b.HasKey("RatingId")
                        .HasName("pk_user_individual_ratings");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("ix_user_individual_ratings_reviewee_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_user_individual_ratings_reviewer_id");

                    b.ToTable("user_individual_ratings", (string)null);
                });

            modelBuilder.Entity("ContractDevApi.Models.UserSkill", b =>
                {
                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("user_account_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("UserAccountId", "SkillId")
                        .HasName("pk_user_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_user_skills_skill_id");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("ContractDevApi.Models.SocialConnection", b =>
                {
                    b.HasOne("ContractDevApi.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_connections_user_accounts_user_account_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ContractDevApi.Models.UserProfile", b =>
                {
                    b.HasOne("ContractDevApi.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_user_accounts_user_account_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ContractDevApi.Models.UserRating", b =>
                {
                    b.HasOne("ContractDevApi.Models.UserAccount", "RevieweeAccount")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_individual_ratings_user_accounts_reviewee_id");

                    b.HasOne("ContractDevApi.Models.UserAccount", "ReviewerAccount")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_individual_ratings_user_accounts_reviewer_id");

                    b.Navigation("RevieweeAccount");

                    b.Navigation("ReviewerAccount");
                });

            modelBuilder.Entity("ContractDevApi.Models.UserSkill", b =>
                {
                    b.HasOne("ContractDevApi.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_skills_skills_skill_id");

                    b.HasOne("ContractDevApi.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_skills_user_accounts_user_account_id");

                    b.Navigation("Skill");

                    b.Navigation("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
